env:
  browser: true
  mocha: true

plugins:
  - import
  - mocha

parser: '@babel/eslint-parser'

parserOptions:
  sourceType: 'module'
  requireConfigFile: false
  babelOptions:
    presets: ["@babel/preset-react"]

extends:
  - standard
  - prettier
  - 'standard-jsx'
  - 'standard-react'

settings:
  react:
    version: '16.8'

rules:
  no-console: 'error'

  # Disable some rules from eslint:recommended.
  no-empty: ['error', { 'allowEmptyCatch': true }]
  # Allow unused parameters. In callbacks, removing them seems to obscure
  # what the functions are doing.
  no-unused-vars: ['error', { 'args': 'none' }]

  # These should be disabled by eslint-config-prettier, but are not.
  react/jsx-curly-spacing: 'off'
  jsx-quotes: 'off'
  # spaced-comment: "off"
  # standard/object-curly-even-spacing: "off"
  # one-var: "off"

  # Shields additions.
  no-var: 'error'
  prefer-const: 'error'
  strict: 'error'
  arrow-body-style: ['error', 'as-needed']
  object-shorthand: ['error', 'properties']
  prefer-template: 'error'

  'mocha/handle-done-callback': 'error'
  'mocha/no-global-tests': 'error'
  'mocha/no-mocha-arrows': 'error'
  'mocha/no-exclusive-tests': 'error'
