version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Install dependencies for the example app
          # Argh, this really should work.
          # command: cd example && npm install
          command: cd example && npm ci

      - save_cache:
          paths:
            - node_modules
            - example/node_modules
          key: v3-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Run the build
          command: npm run build
          when: always

      - run:
          name: Build the example
          command: cd example && npm run build
          when: always

      - run:
          name: Check lint
          command: npm run lint
          when: always

      - run:
          name: Check prettier
          command: npm run prettier-check
          when: always
